#cloud-config
groups:
  - ubuntu: [root,sys]
  - terraform

# Add users to the system. Users are added after groups are added.
users:
  - default
  - name: terraform
    gecos: terraform
    shell: /bin/bash
    primary_group: terraform
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    lock_passwd: false
    ssh_authorized_keys:
      - ${ssh-rsa}

runcmd:
  - sudo apt-get update
  - sudo apt install apache2 -q -y
  - sudo curl https://raw.githubusercontent.com/pgrabarczyk/digitalocean-example/master/src/${service}.html -O
  - sudo curl https://raw.githubusercontent.com/pgrabarczyk/digitalocean-example/master/src/background_${service}.jpg -O
  - sudo rm /var/www/html/index.html
  - sudo mv ${service}.html /var/www/html/index.html
  - sudo mv background_${service}.jpg /var/www/html/
  - sudo systemctl restart apache2